import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';

// Browser paths remain stable for immutable deployments and existing decks.
// No framework runtime, no network imports, no source-map payload on first paint.
for (const [entry, output] of [['src/app.js','app.js'],['src/recipes-entry.js','recipes.js']]) {
  const result = await build({entryPoints:[entry], bundle:true, format:'iife',
    target:'es2020', minify:false, write:false});
  const bytes = '// Generated by npm run build:browser; edit src/, not this file.\n' + result.outputFiles[0].text;
  const path = 'public/' + output;
  if (process.argv.includes('--check')) {
    if (await readFile(path,'utf8').catch(() => '') !== bytes)
      throw new Error(path + ' is stale; run npm run build:browser');
  } else await writeFile(path,bytes);
}
